tilezen/joerd

README.md
config.example.yaml
joerd/command.py
joerd/composite.py
joerd/output/terrarium.py

16-bit PNGs don't display well in the browser, so it's helpful for testing and demoing to be able to generate 8-bit PNGs as well. This adds that functionality, as well as cleaning up a few other things noticed / fixed while deploying to EC2, notably changing the single zoom output to a list of zooms.
Connects to #9.

Support browser PNG

---

joerd/composite.py
joerd/output/skadi.py
joerd/output/terrarium.py
joerd/source/etopo1.py
joerd/source/gmted.py
joerd/source/ned.py
joerd/source/ned_base.py
joerd/source/srtm.py

The Lanczos filter is great for really smooth interpolation, but it doesn't matter as much when reducing the resolution of a data source. It also has the problem that it's susceptible to "ringing", or producing particularly light or dark artefact pixels near the edges of the interpolation.
This changes most of the data sources to flip to cubic interpolation when the source resolution is greater than the destination resolution, which should stop most of these artefacts.
Connects to #12.

Fix lanczos artefacts

---

.gitignore
config.example.yaml
joerd/check.py
joerd/download.py
joerd/source/etopo1.py
joerd/source/gmted.py
joerd/source/ned_base.py
joerd/source/srtm.py
logging.example.config
setup.py
tests/test_download.py

Some download sites (e.g: the GMTED one) have a TCP-layer rate-limiter which simply kills connections. This makes it rather difficult to download large files reliably, which would be required if running Joerd across a large cluster.
This PR adds a download method which is reliable in the sense that it can resume terminated downloads, and is configurable.
Connects to #18.

Make downloads more robust

---

.gitignore
README.md
config.example.yaml
joerd/command.py
joerd/composite.py
joerd/config.py
joerd/output/skadi.py
joerd/output/terrarium.py
joerd/source/etopo1.py
joerd/source/gmted.py
joerd/source/ned.py
joerd/source/ned_base.py
joerd/source/ned_topobathy.py
joerd/source/srtm.py
joerd/srs.py
joerd/util.py
joerd/vrt.py
logging.example.config
tests/test_ned.py
tests/test_srtm.py

A lot of the code for downloading and processing tiles was duplicated in each source. This has now been factored out into the command process. The downloads are now all run through a single queue, which allows them to all be run in parallel, which helps when a small number of requests (e.g: GMTED) take a
disproportionate amount of time to download (and retry, retry, retry...)
Note that this means the `download`, `buildvrt`, `generate` steps are all merged into one, in preparation for #11.
Also the source bounding boxes are now based on the padded extents of the requested regions (fixes #16), and data sources now cache their indexes (fixes #13).
Connects to #19.

Huge refactor. Adds zoom ranges to source selections.

---

config.example.yaml
joerd/command.py
joerd/composite.py
joerd/index.py
joerd/output/skadi.py
joerd/output/terrarium.py
joerd/source/etopo1.py
joerd/source/gmted.py
joerd/source/ned.py
joerd/source/ned_base.py
joerd/source/ned_topobathy.py
joerd/source/srtm.py
logging.example.config
setup.py
tests/test_ned.py
tests/test_terrarium.py

This change allows sources to build a set of VRTs on the fly. This means that the NED source can return a separate VRT for each named region, meaning that the data from each can be used. Previously, they'd all been in the same VRT, which didn't allow for compositing between overlapping parts of differently-named regions.
This also adds an index to the tiles during generation to speed up intersection tests against them.
Connects to #3.

Fix overlapping NED

---

config.example.yaml
joerd/composite.py
joerd/output/terrarium.py

Replace browser PNG with a 3-channel RGB 16.8 fixed point height format. Make GeoTIFF output compressed (LZW, predictor=2).
Note that the blockiness around the coast is flipping between 0, which is non-greenish (green channel = 0), and small negative numbers which are very greenish (green > 200-ish). It looks horrible, but isn't actually a bug. (Although we might want to come back to it far, far down the line when we've solved all the other problems).
Connects to #30.

Add 3-channel 16.8 fixed-point PNGs

---

.gitignore
config.example.yaml
joerd/command.py
joerd/composite.py
joerd/download.py
joerd/output/normal.py
logging.example.config
setup.py

This adds normal maps as a 3rd type of output. Currently it shares a lot of code with the Terrarium tiles, but hopefully we can factor that out in the future.
This is what the tiles look like:
That's the RGB channels on the left and alpha as greyscale on the right, to make it easier to see. With R, G, B, A = X, Y, Z, H where X, Y, Z are the respective components of the normal, scaled with (-1.0, 1.0) mapped to (0, 255) with 0.0 mapped to 128. The A = H component is mapped to a table having:
* -11,000m to -1,000m in 1,000m increments,
* -100m, -50m, -20m, -10m, -1m,
* 0m to 3,000m in 20m increments,
* 3,000m to 6,000m in 50m increments,
* 6,000m to 8,800m in 100m increments.
Note that the indices count from 255 (for -11,000m) down to 0 for 8,800m. This is so that the more common heights …

Add normal maps

---

joerd/output/normal.py

Profiling revealed that the normalisation step was taking the most time. The normalisation step takes the _x_ & _y_ gradients together with a unit _z_ normal and turns that into a unit 3-vector scaled between 0 and 255 (with 0, 0, 0 -> 128, 128, 128). Previously, it was using `apply_along_axis`, but this turns out to be a Bad Idea. Instead, using vector operations the whole way along is (in a microbenchmark) about 320x faster, but it seems that the inner sum of a 3D matrix isn't supported by `numpy.norm`, so we have to use Einstein Sum notation, which looks a bit like magic.
@rmarianski, @kevinkreiser could you review, please?

Use the power of the Einstein Sum for a 300x speedup.

---

joerd/command.py
joerd/composite.py
joerd/download.py
joerd/mask.py
joerd/source/etopo1.py
joerd/source/gmted.py
joerd/source/ned.py
joerd/source/ned_base.py
joerd/source/ned_topobathy.py
joerd/source/srtm.py
joerd/tmpdir.py
joerd/vrt.py
setup.py

Some of the blockiness was coming from using GMTED data with NODATA set in water areas. At zoom 11, it was scaling up and interpolating using the Lanczos filter, which doesn't behave well in the presence of NODATA. Using Bilinear more or less solves this, at the cost of it not looking so great - but it's only intended as backfill for SRTM anyway.
SRTM blockiness was coming from false data in water areas. SRTM ships a "water body" mask raster, so this is now used to mask the water areas. As part of this, the masking step was moved to be part of the download, and now operates at the native resolution of the input dataset.
Sadly, this doesn't solve the problem entirely. For example,
The blockiness around the coastline now is due to resampling errors. But it's better than it was before. I've …

Make coastal blockiness a bit better

---

config.example.yaml
joerd/source/srtm.py

The SRTM mask is optional, but when it's omitted only one argument is passed to the unpack function, which causes an error. This makes the second argument optional, and skips the masking step if it isn't specified.

Fix SRTM missing mask error

---

joerd/command.py
joerd/source/etopo1.py
joerd/source/gmted.py
joerd/source/ned.py
joerd/source/ned_base.py
joerd/source/ned_topobathy.py
joerd/source/srtm.py

..when the current job needs more space than you have.
This fixes #40.
The way it works is by having each datasource generate a list of its cached DEMs, we then subtract from this set the set required by the current job. What remains is a list of DEMs that we could remove if we need the space. We save this list in shared memory and in a synchronized manner, we delete these files when the `unpack` operation fails.
We still need to catch just the exception thrown by unpacking to a full disk though. I'm still testing this so its not quite ready yet. Just wanted to show the diff for easier debugging.

Remove Unneeded Cached DEMs

---

joerd/command.py
joerd/config.py
joerd/output/normal.py
joerd/output/skadi.py
joerd/output/terrarium.py
joerd/source/srtm.py
joerd/store/s3.py
tests/test_srtm.py

This:
* Fixes a bunch of typos and other code mistakes with the SQS / cluster functionality, including: missing the `create` function for the S3 'plugin', missing imports, incorrect usage of the boto3 API.
* Make bounding boxes for jobs slightly smaller than 2x2 degrees, so that they overlap all the tiles we want, but don't touch neighbouring ones which will be generated elsewhere. This reduces the size of the downloads and removes duplicate work.
* Fix typo with Skadi tiles, which was causing them to be generated blank.
* Add support for separate indexes for the data / mask for SRTM. This is because the SRTM masks are not generated / put up online when they are land-only.
* Add recovery mechanism for when a job fails - the queue will ensure it gets retried.
@kevinkreiser could you …

Fix a bunch of bugs, mostly related to clustering.

---

README.md
joerd/command.py
scripts/generate.py

Removed complicated stuff from enqueuer and put it in a separate program, with more options to control output size.
It is now possible to run a config through the `scripts/generate.py`, for example:
```bash
python scripts/generate.py --bbox="-120,36,-118,40" config.yaml config.out.yaml ~/Downloads/natural_earth/ne_10m_*.shp
```
Will generate an output file with many smaller regions. The output config can be passed directly into the enqueuer, which will now just turn each into a job, 1:1.
Note that for production use, the `--bbox` parameter is optional and defaults to global scope. There's also a `--global-region True` argument for adding a global job to do everything below z8.

Options for making smaller jobs.

---

joerd/command.py

so the config has the orignal dict/list yaml loaded but it also has some proper objects in it. seems like the enqueue method wanted to loop over the dicts. so ive made that change and it works (i think) but i have a feeling that this isnt the only change that needs to be done.
so @zerebubuth can you have a look at this to see what the real fix might be :grinning:

actually iterate over configure regions

---

README.md
joerd/command.py
joerd/composite.py
joerd/config.py
joerd/mkdir_p.py
joerd/output/normal.py
joerd/output/skadi.py
joerd/output/terrarium.py
joerd/plugin.py
joerd/queue/fake.py
joerd/queue/sqs.py
joerd/region.py
joerd/server.py
joerd/source/etopo1.py
joerd/source/gmted.py
joerd/source/ned.py
joerd/source/ned_base.py
joerd/source/ned_topobathy.py
joerd/source/srtm.py
joerd/store/file.py
joerd/store/s3.py
joerd/vrt.py
scripts/generate.py

First, apologies for the monster patch...
This backs out a lot of the previous work we've done to make Joerd run efficiently while downloading things on the fly and caching as much as possible. Turns out that was A Bad Design for short-lived spot servers.
In place of that, it reverts to an earlier design with two phases: download and render. There are now two `enqueue-` commands, one for each phase, and a single `server` command. The queue has been abstracted, and a `fake` queue type added which executes any "sent" job immediately.
A download job is for a single source file, and will download it from the source and store it in the `source_store`. A render job is for a single output tile, and will download all its dependencies from the `source_store` to the local filesystem, render the job …

Batch downloading

---

config.example.yaml
joerd/mercator.py
joerd/output/normal.py
joerd/output/terrarium.py
joerd/output/tiff.py
logging.example.config

The `terrarium` output used to handle both PNG and TIFF outputs, but they are now different sizes, so the common code has been factored out into a separate `mercator.py` (and some of the same stuff from normal output as well), and now there are separate TIFF and PNG outputs. The latter retains the terrarium name, as that's what will most likely use the PNGs.
Connects to #58.

Make TIFFs bigger, and internally tiled.

---

joerd/command.py
joerd/store/s3.py
logging.example.config

S3 uploads seem to fail very, very rarely in a way that the `boto` library doesn't seem to want to retry. Given that all the processing is done by the time we upload, it seems like a shame to rely on the queue to retry the whole job. Instead, just loop a few times with exponential backoff to see if we can store the tile.
Also, fix typo / keyword error with the functionality to skip existing downloads.

Retry S3 uploads

---

joerd/store/cache.py

This cache will keep copies of ETOPO1 and GMTED source files on disk. These are the most commonly-used files, and so can provide a significant speed-up to not re-download (measured 2.4x increase in speed).
Current limitations: the cache won't delete files when it is out of space, which may cause problems if there isn't enough free disk space.

Add simple cache

---

joerd/command.py
joerd/dispatcher.py
joerd/download.py
joerd/queue/fake.py
joerd/queue/sqs.py
joerd/server.py
joerd/source/srtm.py
joerd/store/s3.py
joerd/vrt.py
tests/test_dispatcher.py

This adds a new type of job, called "renderbatch", where each job has the same set of sources. This happens frequently with high-zoom tiles and seems to be a good way to enforce re-use. This is done using a `GroupingDispatcher` which maintains a map of the sources to the list of output tiles which share the same set.
Running this on the dev cluster shows a 14x improvement.
Connects to #67.

Group similar jobs

---

joerd/output/normal.py

Numpy arrays index _rows_ as the first number, i.e: `y` rather than `x` first, defying convention. This was causing normal tiles adjacent to world boundaries to be offset by 10 pixels in x, y or both directions.
Also, the 0th row is at the _top_ of the image, so it should have been using the top margin rather than the bottom margin to index from.

Fix bad offsets in normal tiles.

---

circle.yml

I am setting up some proactive connections from upstream documentation repos to the central Mapzen repository. This change will cause CircleCI to trigger rebuilds on that repository, after [merge of PR #233](https://github.com/mapzen/mapzen-docs-generator/pull/223).

Added local-branch deployment command to rebuild docs

---

docs/data-sources.md
docs/use-service.md

Part of https://github.com/mapzen/documentation/issues/310
Also updates the attribution.md link to point to GitHub source after it was removed from published docs.

Change underscores to hyphens in placeholder api key

---

docs/use-service.md

This should only get merged once the buffered terrain service is in production, and we are ready to go public with it.

Add docs about tile size variants

---

docs/use-service.md

Including specifying 512 and zoom 14 max to fix #156.
Vector tile changes are over in https://github.com/tilezen/vector-datasource/pull/1399.
Like that other PR: This is off the `v1.0.0-docs11` branch that happens for docs to be the same as master. This PR should be merged to master before the v2 PR, and then we can just tag master as 
`v1.0.0-docs12` and releasing as latest will trigger Mapzen docs update.

[docs] better 512 px tile size documenation
