.gitignore
config.example.yaml
joerd/source/ned.py
logging.example.config
tests/test_ned.py

This is the first attempt at adding a NED data source. There are some outstanding issues, which I've punted to #2 and #3; respectively, that at least one file fails to download in an interesting way, and that NED contains many overlapping data files and it would be best to not download all of them (at the moment, I've set it to only download the "topobathymetry" ones, but they don't seem to have full coverage by themselves.
Connects to #1.

Add first try at a NED data source.

---

config.example.yaml
joerd/command.py
joerd/config.py
joerd/output/skadi.py
joerd/output/terrarium.py
joerd/source/etopo1.py
joerd/source/gmted.py
joerd/source/ned.py
joerd/source/srtm.py
setup.py

Updated sources and outputs to not contain any hard-coded paths. All these are passed through from the config file.
Connects to #5.

Made sources and outputs configurable.

---

joerd/output/terrarium.py

In addition to outputting Int16 GeoTIFFs, output UInt16 greyscale PNGs.
Connects to #9.

Create PNG outputs for terrarium tiles.

---

config.example.yaml
joerd/source/ned.py
joerd/source/ned_base.py
joerd/source/ned_topobathy.py
tests/test_ned.py

This should help to alleviate the overlapping nature of the files doesn't cause too many problems.
Connects to #3.

Split NED into topology and topobathy parts

---

joerd/command.py

Ooops, forgot to delete the message after we are done processing it.

---

joerd/output/skadi.py

Add compression for Skadi output tiles.

---

joerd/command.py

Interpret path to logging config to be relative to the main config file.

---

joerd/download.py

The try-catch block should cover the whole of the download, and the download isn't done until `f` has been completely copied to `tmp`, or it died in the process.

Catch socket timeouts in download

---

joerd/output/terrarium.py

Add options for disabling both TIF and PNG output, as we may want to enable/disable each individually.
The default is to enable both, so to (e.g:) disable PNG, the config would need to say:
```yaml
outputs:
- type: terrarium
enable_png: false
```
Note that I also removed the old `enable_browser_png` option, as that format went away in a previous commit and the option wasn't being used.

Add terrarium output formats

---

config.example.yaml
joerd/source/ned13.py

Adds a 1/3rd arcsecond NED data source.
Connects to #62.

Add 1/3rd arcsecond NED data source.

---

CONTRIBUTING.md

Documented the process in #82, which unfortunately wasn't as simple as I'd have liked.

Add documentation around contributing a new data source.

---

config.example.yaml
joerd/check.py
joerd/command.py
joerd/mask.py
joerd/source/greatlakes.py
joerd/srs.py

Adds NOAA data for the Great Lakes - primarily bathymetry. This isn't a tiled data set, and one image corresponds to one lake. This can just about be shoe-horned into the existing Joerd structure, but exposes a few design flaws.
Connects to #23.

Add Great Lakes data

---

docs/api-keys-and-rate-limits.md
docs/use-service.md

went ahead and got the docs ready for unified keys

update for unified keys

---

docs/build-a-map.md
docs/formats.md
docs/index.md
docs/use-service.md

Adding some edits to the docs, per https://github.com/mapzen/mapzen-docs-generator/pull/205 's request.

Docs Tweaks

---

README.md

@nvkelso could you review, please?

Add caveat section to the docs to warn about this GDAL bug.

---

docs/formats.md
docs/index.md
docs/use-service.md

removing the link for the terrain project page since that doesn't really exist yet. thanks for catching @meetar @rmglennon

updating project link

---

docs/api-keys-and-rate-limits.md
docs/use-service.md

remove API key information to redirect to /documentation/overview, re: #110

update api key info

---

docs/attribution.md
docs/data-sources.md
docs/formats.md

fixes #112 changing the attribution requirements, per @nvkelso's copy. 
My only question is if it's confusing to include the self-hosted requirements?

add attribution requirements

---

docs/LICENSE.md

Needs to be paired with docs generator update to ignore `LICENSE.md` file.

WIP: clarify docs license to CC-BY

---

circle.yml

fixes https://github.com/mapzen/mapzen-docs-generator/issues/243 
and adds the new documentation CircleCI build

add new tickle process

---

circle.yml
docs/examples/collect.py

Add Mapzen API key to terrain collect script

---

docs/formats.md
docs/index.md

adding some words to describe `raw latlng` more coherently

update descriptions of GCS

---

docs/use-service.md

a few typos, also standardizing on US spelling of "neighboring"

misc typos
